### ISSUE TITLE
 Use two rangeslider in one page

### ISSUE THREAD

**Issue by vre142** [nanjingboy/ZMSwiftRangeSlider#1]
Hi,
I want to use three of this library range slider in one page how can I detect them?
Thanks,
Vafa

**Comment by nanjingboy** [comment]
Sorry delay so long, please upgrade this with

```ruby
pod 'ZMSwiftRangeSlider', '~> 0.1.3'
```

and see the [Example](https://github.com/nanjingboy/ZMSwiftRangeSlider/blob/master/Example/Example/ViewController.swift)
