### ISSUE TITLE
Can not install 0.1.5 version

### ISSUE THREAD

**Issue by ViktorRudyk** [nanjingboy/ZMSwiftRangeSlider#3]
Hi!
tried to install 0.1.5 version with CocoaPods and received an error
(version 0.1.3 installs with no problems )
CocoaPods: 1.1.1 
Xcode: 8.1

Error:
########################################

[!] Unable to satisfy the following requirements:

\- `ZMSwiftRangeSlider (~> 0.1.5)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `ZMSwiftRangeSlider (~> 0.1.5)`.

You have either:
 \* out-of-date source repos which you can update with `pod repo update`.
 \* mistyped the name or version.
 \* not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

#########################################

Here is the content of my  Podfile
#########################################

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Test' do
    pod 'ZMSwiftRangeSlider', '~> 0.1.5'
end

#########################################

**Comment by nanjingboy** [comment]
please try `pod repo update` first

**Comment by ViktorRudyk** [comment]
It didn't help. 
"pod repo update" throws another error:

[!] No `Podfile.lock' found in the project directory, run `pod install'.

**Comment by nanjingboy** [comment]
The error message has told you.

**Comment by ViktorRudyk** [comment]
Ok, I realised it: 
I was trying to run "pod repo update" before "pod install" what is not possible.

So :
1) I have run "pod install" (it has created some necessary files and thrown the first error)
2) then have run "pod repo update"  - have been waiting for really too long time until it has finished updating
3) then have run "pod install" once more  - and all is working

Thanks a lot! :)
