### ISSUE TITLE
use for swift 2.3

### ISSUE THREAD

**Issue by vre142** [nanjingboy/ZMSwiftRangeSlider#7]
Hi,
Excuse Me How can I use this library with swift 2.3?
because I have a lot of error when I use it now

**Comment by nanjingboy** [comment]
Please use version 0.1.3

**Comment by vre142** [comment]
I use 0.1.3 but when i want to install it with cocoa pods it's automatic use 0.1.5 
how can i du?

**Comment by nanjingboy** [comment]
pod 'ZMSwiftRangeSlider', '~> 0.1.3'
