### ISSUE TITLE
How to set the minimum nd maximum value of slider?

### ISSUE THREAD

**Issue by Singh09Meenu** [nanjingboy/ZMSwiftRangeSlider#9]
Can I put the slider minimum nd maximum value??

**Comment by nanjingboy** [comment]
I'll add these features in next version, so please just wait for a few days

**Comment by nanjingboy** [comment]
@Singh09Meenu Hi, you can upgrade the library and set min & max value like this: https://github.com/nanjingboy/ZMSwiftRangeSlider/blob/master/Example/Example/ViewController.swift#L23

**Comment by Singh09Meenu** [comment]
Hi,
Tom

I have done the updation but their is an error showing after updation in
TextLayer.Swift file can u please check that out.


regards,
Meenu

**Comment by nanjingboy** [comment]
@Singh09Meenu can you give more details?

**Comment by nanjingboy** [comment]
@Singh09Meenu sorry, I can't find anything about the error detail from your comments

**Comment by nanjingboy** [comment]
@Singh09Meenu sorry, I can't find anything about the error detail from your comments

**Comment by Singh09Meenu** [comment]
Hi,Have u seen the attachment?

**Comment by Singh09Meenu** [comment]
Hi,
I am getting error in  Textlayer.swift page on the line no. 14

this is the line -

 self.alignmentMode = CATextLayerAlignmentMode.center


nd error  is - Type 'CATextLayerAlignmentMode' (aka 'NSString') has no
member 'center'.


I want to know one thing more is their any way to set the image on slider
thumbnail .I have to do that but I m unable to do in this pod file.






Thanks & Regards

Meenu

**Comment by nanjingboy** [comment]
@Singh09Meenu  

1.  to fix the error you should upgrade swift version to 4.0
2.  you can't set the image on slider thumbnail for now

**Comment by Singh09Meenu** [comment]
Hi Tom,
See I have the Xcode version 10.0 and it is updated only .
IS their any way to set image by my own actually I m need to set image
also.If I m unable to do that then I. have to go for another pod file which
I don't want.


Thanks & Regards
Meenu

**Comment by nanjingboy** [comment]
@Singh09Meenu sorry delay so long,  you can fork this repo and change [ThumbLayer.swift](/Source/ThumbLayer.swift) with your own logic.

**Comment by Singh09Meenu** [comment]
Thanks.
